CS240Project: ChessGuiBoard Class Reference
ChessGuiBoard Class Reference
ChessGuiBoard is a data structure for manipulating a 2d array of ChessGuiBoardCell.
#include <ChessGuiBoard.h>
Public Member Functions
ChessGuiBoard (BaseObjectType *cobject, const Glib::RefPtr< Gnome::Glade::Xml > &refGlade)
This format of constructor is necessary for this constructor to be automatically used by the Glade::Xml::get_derived_widget() function.
void RefreshBoard ()
UpdateImage for each cell in board.
void ResizeBoard (int width, int height)
~ChessGuiBoard ()
Glade::Xml handles destroying Widgets.
Cell Manipulation
void HighlightSquare (signed int row, signed int col, guint32 color)
void UnHighlightSquare (signed int row, signed int col)
void PlacePiece (signed int row, signed int col, ImageName piece)
void ClearPiece (signed int row, signed int col)
Signal Accessors
sigc::signal< void, int, int, int > signal_cell_selected ()
emited when a butten is pressed over a square
sigc::signal< void, int, int > signal_drag_start ()
emited when button 1 is pressed, held, and then the mouse is moved
sigc::signal< bool, int, int > signal_drag_end ()
emited after a drag has been initiated and the button has been released
Private Member Functions
void ConnectCellSignals (ChessGuiBoardCell *cell, Gtk::EventBox *eb, int row, int col)
void InitCell (const Glib::RefPtr< Gnome::Glade::Xml > &chessXml, int row, int col)
Internal Signal Handlers
void on_board_size_allocate (Gtk::Allocation &allocation)
Connected to the signal_size_allocate emmited by an EventBox containing this widget.
bool on_button_released (GdkEventButton *event, int row, int col)
Emits signal_cell_selected if a drag hasn't been initiated and then terminated outside of this square.
bool on_button_pressed (GdkEventButton *event, int row, int col)
void on_cell_drag_begin (const Glib::RefPtr< Gdk::DragContext > &context, int row, int col)
bool on_cell_drag_drop (const Glib::RefPtr< Gdk::DragContext > &context, int x, int y, guint time, int row, int col)
void on_cell_drag_leave (const Glib::RefPtr< Gdk::DragContext > &context, guint time, int row, int col)
bool on_cell_drag_motion (const Glib::RefPtr< Gdk::DragContext > &context, int x, int y, guint time, int row, int col)
Static Private Member Functions
static std::string GenStringName (int row, int col)
Generates a string using the name scheme ("ChessBoard_Row%d_Col%d", row,col) Used in retrieving widgets from refGlade.
Private Attributes
ChessGuiBoardCell * board [NUM_ROW][NUM_COL]
int curCellCol
col of the last cell that activated a button_pressed event.
int curCellRow
row of the last cell that activated a button_pressed event.
bool dragStarted
indicates wether a drag has been initiated.
int height
Current height of the AspectFrame as assigned by the parent widget.
int width
Current width of the AspectFrame as assigned by the parent widget.
signals
sigc::signal< void, int, int, int > cellSelectSignal
sigc::signal< void, int, int > dragStartSignal
sigc::signal< bool, int, int > dragEndSignal
Detailed Description
ChessGuiBoard is a data structure for manipulating a 2d array of ChessGuiBoardCell.
It's functionality is completely wrapped inside of the ChessGui class and so never needs to be accessed directly by the student
Note:
Depends heavily on cs240chess.glade
Constructor & Destructor Documentation
ChessGuiBoard::ChessGuiBoard (BaseObjectType * cobject, const Glib::RefPtr< Gnome::Glade::Xml > & refGlade)
This format of constructor is necessary for this constructor to be automatically used by the Glade::Xml::get_derived_widget() function.
See "Glade File"
Parameters:
cobject initialize Gtk::Window
refGlade is generated beforehand using libglademm
References DEFAULT_BOARD_HEIGHT, DEFAULT_BOARD_WIDTH, height, InitCell(), NUM_COL, NUM_ROW, on_board_size_allocate(), and width.
ChessGuiBoard::~ChessGuiBoard ()
Glade::Xml handles destroying Widgets.
References board, NUM_COL, and NUM_ROW.
Member Function Documentation
void ChessGuiBoard::ClearPiece (signed int row, signed int col)
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
References board, NUM_COL, NUM_ROW, PIECE_LAYER, ChessGuiBoardCell::SetLayerVisible(), and ChessGuiBoardCell::UpdateImage().
Referenced by ChessGui::ClearPiece().
void ChessGuiBoard::ConnectCellSignals (ChessGuiBoardCell * cell, Gtk::EventBox * eb, int row, int col) [private]
connect button pressed/released events
set cell as drag-and-dropable
set up drag/drop handlers
References on_button_pressed(), on_button_released(), on_cell_drag_begin(), on_cell_drag_drop(), on_cell_drag_leave(), and on_cell_drag_motion().
Referenced by InitCell().
std::string ChessGuiBoard::GenStringName (int row, int col) [static, private]
Generates a string using the name scheme ("ChessBoard_Row%d_Col%d", row,col) Used in retrieving widgets from refGlade.
Parameters:
row 1-8
col 1-8
Referenced by InitCell().
void ChessGuiBoard::HighlightSquare (signed int row, signed int col, guint32 color)
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
color RRGGBBAA hexadecimal value see ChessGuiDefines.h
References board, NUM_COL, NUM_ROW, ChessGuiBoardCell::SetHiglightLayer(), and ChessGuiBoardCell::UpdateImage().
Referenced by ChessGui::HighlightSquare().
void ChessGuiBoard::InitCell (const Glib::RefPtr< Gnome::Glade::Xml > & chessXml, int row, int col) [private]
Retrieve widget from Glade::Xml and place on board
retrieve EventBox container for this widget and connect event signals
set background layer
set tile pattern
References BACK_GRND, BLACK_TILE, board, ConnectCellSignals(), GenStringName(), ChessGuiImages::GetImage(), NUM_COL, NUM_ROW, ChessGuiBoardCell::SetBackGroundLayer(), ChessGuiBoardCell::SetTileLayer(), ChessGuiBoardCell::UpdateImage(), and WHITE_TILE.
Referenced by ChessGuiBoard().
void ChessGuiBoard::on_board_size_allocate (Gtk::Allocation & allocation) [private]
Connected to the signal_size_allocate emmited by an EventBox containing this widget.
References ResizeBoard().
Referenced by ChessGuiBoard().
bool ChessGuiBoard::on_button_pressed (GdkEventButton * event, int row, int col) [private]
set curCellRow and curCellCol
References curCellCol, curCellRow, and dragStarted.
Referenced by ConnectCellSignals().
bool ChessGuiBoard::on_button_released (GdkEventButton * event, int row, int col) [private]
Emits signal_cell_selected if a drag hasn't been initiated and then terminated outside of this square.
References curCellCol, curCellRow, dragStarted, signal_cell_selected(), and signal_drag_end().
Referenced by ConnectCellSignals().
void ChessGuiBoard::on_cell_drag_begin (const Glib::RefPtr< Gdk::DragContext > & context, int row, int col) [private]
Set the Drag Icon
set curCellRow and curCellCol
emit signal_drag_start()
References board, curCellCol, curCellRow, dragStarted, PIECE_LAYER, and signal_drag_start().
Referenced by ConnectCellSignals().
bool ChessGuiBoard::on_cell_drag_drop (const Glib::RefPtr< Gdk::DragContext > & context, int x, int y, guint time, int row, int col) [private]
emits signal_drag_end
References dragStarted, and signal_drag_end().
Referenced by ConnectCellSignals().
void ChessGuiBoard::on_cell_drag_leave (const Glib::RefPtr< Gdk::DragContext > & context, guint time, int row, int col) [private]
References curCellCol, and curCellRow.
Referenced by ConnectCellSignals().
bool ChessGuiBoard::on_cell_drag_motion (const Glib::RefPtr< Gdk::DragContext > & context, int x, int y, guint time, int row, int col) [private]
updates curCellRow and curCellCol
References curCellCol, and curCellRow.
Referenced by ConnectCellSignals().
void ChessGuiBoard::PlacePiece (signed int row, signed int col, ImageName piece)
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
piece valid piece as define in ImageName
References board, ChessGuiImages::GetImage(), NUM_COL, NUM_IMAGE_NAMES, NUM_ROW, ChessGuiBoardCell::SetPieceLayer(), ChessGuiBoardCell::UpdateImage(), and W_PAWN.
Referenced by ChessGui::PlacePiece().
void ChessGuiBoard::RefreshBoard ()
UpdateImage for each cell in board.
References board, NUM_COL, NUM_ROW, and ChessGuiBoardCell::UpdateImage().
Referenced by ChessGui::on_LoadImages().
void ChessGuiBoard::ResizeBoard (int width, int height)
Parameters:
width total width (of all cells) of the board
height total height (of all cells) of the board
Does not resize if board is already same size
References board, CELL_PAD, ChessGuiBoardCell::height, height, NUM_COL, NUM_ROW, ChessGuiBoardCell::UpdateImage(), ChessGuiBoardCell::width, and width.
Referenced by on_board_size_allocate().
sigc::signal< void, int, int, int > ChessGuiBoard::signal_cell_selected ()
emited when a butten is pressed over a square
Note:
If the button 1 is pressed and a drag is initiated, signal will only be emitted if the drage terminates in the same square
signal handler has form void on_cell_selected(int row, int col, int button);
References cellSelectSignal.
Referenced by on_button_released(), and ChessGui::signal_cell_selected().
sigc::signal< bool, int, int > ChessGuiBoard::signal_drag_end ()
emited after a drag has been initiated and the button has been released
Note:
signal handler has the form bool on_drag_end(int endRow, int endCol);
signal handler should return false if drag was invalid
if the drag is terminated outside of the playing area, the intial squares coordinates are returned
References dragEndSignal.
Referenced by on_button_released(), on_cell_drag_drop(), and ChessGui::signal_drag_end().
sigc::signal< void, int, int > ChessGuiBoard::signal_drag_start ()
emited when button 1 is pressed, held, and then the mouse is moved
Note:
signal handler has the form void on_drag_start(int startRow, int endRow);
References dragStartSignal.
Referenced by on_cell_drag_begin(), and ChessGui::signal_drag_start().
void ChessGuiBoard::UnHighlightSquare (signed int row, signed int col)
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
References board, HIGHLIGHT_LAYER, NUM_COL, NUM_ROW, ChessGuiBoardCell::SetLayerVisible(), and ChessGuiBoardCell::UpdateImage().
Referenced by ChessGui::UnHighlightSquare().
Member Data Documentation
ChessGuiBoardCell* ChessGuiBoard::board[NUM_ROW][NUM_COL] [private]
Referenced by ClearPiece(), HighlightSquare(), InitCell(), on_cell_drag_begin(), PlacePiece(), RefreshBoard(), ResizeBoard(), UnHighlightSquare(), and ~ChessGuiBoard().
sigc::signal<void, int, int, int> ChessGuiBoard::cellSelectSignal [private]
Referenced by signal_cell_selected().
int ChessGuiBoard::curCellCol [private]
col of the last cell that activated a button_pressed event.
Used for drag and drop/cell selection
Referenced by on_button_pressed(), on_button_released(), on_cell_drag_begin(), on_cell_drag_leave(), and on_cell_drag_motion().
int ChessGuiBoard::curCellRow [private]
row of the last cell that activated a button_pressed event.
Used for drag and drop/cell selection
Referenced by on_button_pressed(), on_button_released(), on_cell_drag_begin(), on_cell_drag_leave(), and on_cell_drag_motion().
sigc::signal<bool, int, int> ChessGuiBoard::dragEndSignal [private]
Referenced by signal_drag_end().
bool ChessGuiBoard::dragStarted [private]
indicates wether a drag has been initiated.
Prevents emission of both dragEnd and cellSelect signals
Referenced by on_button_pressed(), on_button_released(), on_cell_drag_begin(), and on_cell_drag_drop().
sigc::signal<void, int, int> ChessGuiBoard::dragStartSignal [private]
Referenced by signal_drag_start().
int ChessGuiBoard::height [private]
Current height of the AspectFrame as assigned by the parent widget.
Referenced by ChessGuiBoard(), and ResizeBoard().
int ChessGuiBoard::width [private]
Current width of the AspectFrame as assigned by the parent widget.
Referenced by ChessGuiBoard(), and ResizeBoard().
The documentation for this class was generated from the following files:
ChessGuiBoard.h
ChessGuiBoard.cpp