CS240Project: Board Class Reference
Board Class Reference
An interface for the Board class.
#include <Board.h>
Public Member Functions
void BindCellsToPieces (Pieces *pieces)
Binds each cell to a piece in pieces.
Board ()
Allocates an 8x8 array of Cell pointers and the respective Cells on the heap Each of these Cells is initialized to point to emptyPiece.
Cell * GetCell (int row, int col)
std::string & toString (int numTabs)
toString method
~Board ()
Deletes the Cells and the array of Cell pointers.
Private Attributes
Cell *** cells
Points to array of Cell pointers.
Detailed Description
An interface for the Board class.
This class represents a chess board whose 64 cells (and therefore pieces) can be acessed via row & column indeces
Constructor & Destructor Documentation
Board::Board ()
Allocates an 8x8 array of Cell pointers and the respective Cells on the heap Each of these Cells is initialized to point to emptyPiece.
Note:
IMPORTANT: This is only part of the board's initialization. After declaring a Pieces object, we need to call BindCellsToPieces to finish setting the board.
References cells, and DbgMsg.
Board::~Board ()
Deletes the Cells and the array of Cell pointers.
References cells, and DbgMsg.
Member Function Documentation
void Board::BindCellsToPieces (Pieces * pieces)
Binds each cell to a piece in pieces.
References Cell::BindToPiece(), cells, DbgMsg, Pieces::gBlackBishop0(), Pieces::gBlackBishop1(), Pieces::gBlackKing(), Pieces::gBlackKnight0(), Pieces::gBlackKnight1(), Pieces::gBlackPawn0(), Pieces::gBlackPawn1(), Pieces::gBlackPawn2(), Pieces::gBlackPawn3(), Pieces::gBlackPawn4(), Pieces::gBlackPawn5(), Pieces::gBlackPawn6(), Pieces::gBlackPawn7(), Pieces::gBlackQueen(), Pieces::gBlackRook0(), Pieces::gBlackRook1(), Pieces::gWhiteBishop0(), Pieces::gWhiteBishop1(), Pieces::gWhiteKing(), Pieces::gWhiteKnight0(), Pieces::gWhiteKnight1(), Pieces::gWhitePawn0(), Pieces::gWhitePawn1(), Pieces::gWhitePawn2(), Pieces::gWhitePawn3(), Pieces::gWhitePawn4(), Pieces::gWhitePawn5(), Pieces::gWhitePawn6(), Pieces::gWhitePawn7(), Pieces::gWhiteQueen(), Pieces::gWhiteRook0(), and Pieces::gWhiteRook1().
Referenced by ChessGame::ChessGame().
Cell * Board::GetCell (int row, int col)
Parameters:
row and
col correspond to those used in ChessController
References cells.
Referenced by Cell::Bk(), Cell::Fd(), ChessGame::GetCell(), ChessGame::GetPiece(), Cell::Left(), Pieces::Pieces(), ChessGame::PlayerInCheck(), and Cell::Right().
std::string& Board::toString (int numTabs)
toString method
Member Data Documentation
Cell*** Board::cells [private]
Points to array of Cell pointers.
Referenced by BindCellsToPieces(), Board(), GetCell(), and ~Board().
The documentation for this class was generated from the following files:
Board.h
Board.cpp