CS240Project: Chess Gui Convenience Functions
Chess Gui Convenience Functions
These functions allow for a simple use of the ChessGui interface.
Functions
virtual void Chess::ClearMessageArea ()
Clear all data in the Message Area.
virtual void ChessView::ClearMessageArea ()=0
Clear all data in the Message Area.
virtual void Chess::ClearPiece (signed int row, signed int col)
virtual void ChessView::ClearPiece (signed int row, signed int col)=0
virtual void ChessView::HighlightSquare (signed int row, signed int col, guint32 color)=0
virtual void Chess::HighlightSquare (signed int row, signed int col, guint32 color)
virtual void ChessView::PlacePiece (signed int row, signed int col, ImageName piece)=0
virtual void Chess::PlacePiece (signed int row, signed int col, ImageName piece)
virtual std::string ChessView::SelectLoadFile ()=0
Opens a Gtk::FileChooserDialog in the FILE_OPEN mode.
virtual std::string Chess::SelectLoadFile ()
Opens a Gtk::FileChooserDialog in the FILE_OPEN mode.
virtual std::string ChessView::SelectSaveFile ()=0
Opens a Gtk::FileChooserDialog in the FILE_SAVE mode.
virtual std::string Chess::SelectSaveFile ()
Opens a Gtk::FileChooserDialog in the FILE_SAVE mode.
virtual void ChessView::SetBottomLabel (const std::string &text)=0
Place text in area below the chess board.
virtual void Chess::SetBottomLabel (const std::string &text)
Place text in area below the chess board.
virtual void Chess::SetStatusBar (const std::string &status)
Set text in the Statusbar located at the bottom of the ChessGui.
virtual void ChessView::SetStatusBar (const std::string &status)=0
Set text in the Statusbar located at the bottom of the ChessGui.
virtual void Chess::SetTopLabel (const std::string &text)
Place text in area above the chess board.
virtual void ChessView::SetTopLabel (const std::string &text)=0
Place text in area above the chess board.
virtual void Chess::UnHighlightSquare (signed int row, signed int col)
virtual void ChessView::UnHighlightSquare (signed int row, signed int col)=0
virtual void Chess::WriteMessageArea (const std::string &message)
Write a string to the Message Area.
virtual void ChessView::WriteMessageArea (const std::string &message)=0
Write a string to the Message Area.
Chess Gui Convenience Functions
void ChessGui::SetTopLabel (const std::string &text)
Place text in area above the chess board.
void ChessGui::SetBottomLabel (const std::string &text)
Place text in area below the chess board.
void ChessGui::ClearMessageArea ()
Clear all data in the Message Area.
void ChessGui::WriteMessageArea (const std::string &message)
Write a string to the Message Area.
void ChessGui::SetStatusBar (const std::string &status)
Set text in the Statusbar located at the bottom of the ChessGui.
std::string ChessGui::SelectSaveFile ()
Opens a Gtk::FileChooserDialog in the FILE_SAVE mode.
std::string ChessGui::SelectLoadFile ()
Opens a Gtk::FileChooserDialog in the FILE_OPEN mode.
void ChessGui::HighlightSquare (signed int row, signed int col, guint32 color)
void ChessGui::UnHighlightSquare (signed int row, signed int col)
void ChessGui::PlacePiece (signed int row, signed int col, ImageName piece)
void ChessGui::ClearPiece (signed int row, signed int col)
Detailed Description
These functions allow for a simple use of the ChessGui interface.
Function Documentation
void Chess::ClearMessageArea () [virtual, inherited]
Clear all data in the Message Area.
Implements ChessView.
References ChessGui::ClearMessageArea(), and Chess::gui.
void ChessGui::ClearMessageArea () [inherited]
Clear all data in the Message Area.
References ChessGui::messageArea.
Referenced by Chess::ClearMessageArea(), and ChessGui::on_ClearMessages().
virtual void ChessView::ClearMessageArea () [pure virtual, inherited]
Clear all data in the Message Area.
Implemented in Chess.
void Chess::ClearPiece (signed int row, signed int col) [virtual, inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
Implements ChessView.
References ChessGui::ClearPiece(), and Chess::gui.
virtual void ChessView::ClearPiece (signed int row, signed int col) [pure virtual, inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
Implemented in Chess.
Referenced by ChessControllerImpl::UpdateView().
void ChessGui::ClearPiece (signed int row, signed int col) [inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
References ChessGui::board, and ChessGuiBoard::ClearPiece().
Referenced by Chess::ClearPiece().
void ChessGui::HighlightSquare (signed int row, signed int col, guint32 color) [inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
color RRGGBBAA hexadecimal value see ChessGuiDefines.h
References ChessGui::board, and ChessGuiBoard::HighlightSquare().
Referenced by Chess::HighlightSquare().
void Chess::HighlightSquare (signed int row, signed int col, guint32 color) [virtual, inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
color RRGGBBAA hexadecimal value see ChessGuiDefines.h
Implements ChessView.
References Chess::gui, and ChessGui::HighlightSquare().
virtual void ChessView::HighlightSquare (signed int row, signed int col, guint32 color) [pure virtual, inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
color RRGGBBAA hexadecimal value see ChessGuiDefines.h
Implemented in Chess.
Referenced by ChessControllerImpl::HighlightValidMoves(), and ChessControllerImpl::UpdateView().
virtual void ChessView::PlacePiece (signed int row, signed int col, ImageName piece) [pure virtual, inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
piece valid piece as define in ImageName
Implemented in Chess.
Referenced by ChessControllerImpl::UpdateView().
void ChessGui::PlacePiece (signed int row, signed int col, ImageName piece) [inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
piece valid piece as define in ImageName
References ChessGui::board, and ChessGuiBoard::PlacePiece().
Referenced by Chess::PlacePiece().
void Chess::PlacePiece (signed int row, signed int col, ImageName piece) [virtual, inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
piece valid piece as define in ImageName
Implements ChessView.
References Chess::gui, and ChessGui::PlacePiece().
std::string ChessGui::SelectLoadFile () [inherited]
Opens a Gtk::FileChooserDialog in the FILE_OPEN mode.
Returns:
Path to the file selected
Referenced by Chess::SelectLoadFile().
virtual std::string ChessView::SelectLoadFile () [pure virtual, inherited]
Opens a Gtk::FileChooserDialog in the FILE_OPEN mode.
Returns:
Path to the file selected
Implemented in Chess.
std::string Chess::SelectLoadFile () [virtual, inherited]
Opens a Gtk::FileChooserDialog in the FILE_OPEN mode.
Returns:
Path to the file selected
Implements ChessView.
References Chess::gui, and ChessGui::SelectLoadFile().
std::string Chess::SelectSaveFile () [virtual, inherited]
Opens a Gtk::FileChooserDialog in the FILE_SAVE mode.
Returns:
Path to the file selected
Implements ChessView.
References Chess::gui, and ChessGui::SelectSaveFile().
std::string ChessGui::SelectSaveFile () [inherited]
Opens a Gtk::FileChooserDialog in the FILE_SAVE mode.
Returns:
Path to the file selected
Referenced by Chess::SelectSaveFile().
virtual std::string ChessView::SelectSaveFile () [pure virtual, inherited]
Opens a Gtk::FileChooserDialog in the FILE_SAVE mode.
Returns:
Path to the file selected
Implemented in Chess.
void Chess::SetBottomLabel (const std::string & text) [virtual, inherited]
Place text in area below the chess board.
Parameters:
text
Implements ChessView.
References Chess::gui, and ChessGui::SetBottomLabel().
virtual void ChessView::SetBottomLabel (const std::string & text) [pure virtual, inherited]
Place text in area below the chess board.
Parameters:
text
Implemented in Chess.
void ChessGui::SetBottomLabel (const std::string & text) [inherited]
Place text in area below the chess board.
Parameters:
text
References ChessGui::bottom.
Referenced by Chess::SetBottomLabel().
void ChessGui::SetStatusBar (const std::string & status) [inherited]
Set text in the Statusbar located at the bottom of the ChessGui.
Parameters:
status
References ChessGui::statusbar.
Referenced by Chess::SetStatusBar().
virtual void ChessView::SetStatusBar (const std::string & status) [pure virtual, inherited]
Set text in the Statusbar located at the bottom of the ChessGui.
Parameters:
status
Implemented in Chess.
void Chess::SetStatusBar (const std::string & status) [virtual, inherited]
Set text in the Statusbar located at the bottom of the ChessGui.
Parameters:
status
Implements ChessView.
References Chess::gui, and ChessGui::SetStatusBar().
void ChessGui::SetTopLabel (const std::string & text) [inherited]
Place text in area above the chess board.
Parameters:
text
References ChessGui::top.
Referenced by Chess::SetTopLabel().
virtual void ChessView::SetTopLabel (const std::string & text) [pure virtual, inherited]
Place text in area above the chess board.
Parameters:
text
Implemented in Chess.
void Chess::SetTopLabel (const std::string & text) [virtual, inherited]
Place text in area above the chess board.
Parameters:
text
Implements ChessView.
References Chess::gui, and ChessGui::SetTopLabel().
void ChessGui::UnHighlightSquare (signed int row, signed int col) [inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
References ChessGui::board, and ChessGuiBoard::UnHighlightSquare().
Referenced by Chess::UnHighlightSquare().
void Chess::UnHighlightSquare (signed int row, signed int col) [virtual, inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
Implements ChessView.
References Chess::gui, and ChessGui::UnHighlightSquare().
virtual void ChessView::UnHighlightSquare (signed int row, signed int col) [pure virtual, inherited]
Parameters:
row 0 <= row < NUM_COL, top to bottom
col 0 <= row < NUM_COL, left to right
Implemented in Chess.
Referenced by ChessControllerImpl::UpdateView().
virtual void ChessView::WriteMessageArea (const std::string & message) [pure virtual, inherited]
Write a string to the Message Area.
Parameters:
message
Implemented in Chess.
void ChessGui::WriteMessageArea (const std::string & message) [inherited]
Write a string to the Message Area.
Parameters:
message
References ChessGui::messageArea, and ChessGui::messageWindow.
Referenced by Chess::WriteMessageArea().
void Chess::WriteMessageArea (const std::string & message) [virtual, inherited]
Write a string to the Message Area.
Parameters:
message
Implements ChessView.
References Chess::gui, and ChessGui::WriteMessageArea().