CS240Project: ChessGuiBoardCell Class Reference
ChessGuiBoardCell Class Reference
Provides functionality for drawing layered images to each cell of a ChessGuiBoard.
#include <ChessGuiBoardCell.h>
Public Member Functions
ChessGuiBoardCell (BaseObjectType *cobject, const Glib::RefPtr< Gnome::Glade::Xml > &refGlade)
This format of constructor is necessary for this constructor to be automatically used by the Glade::Xml::get_derived_widget() function.
Private Member Functions
~ChessGuiBoardCell ()
Image Manipulation
No changes appear to image until a call to UpdateImage is made
void UpdateImage ()
Draw all visible layers to image.
void SetLayer (const Glib::RefPtr< Gdk::Pixbuf > &pix, CellLayer layer, bool visible=true, signed int alpha=255)
void SetLayerVisible (CellLayer layer, bool visible=true)
sets wheter a layer should be drawn or not
void SetBackGroundLayer (const Glib::RefPtr< Gdk::Pixbuf > &bg)
Passes appropriate arguments to SetLayer.
void SetTileLayer (const Glib::RefPtr< Gdk::Pixbuf > &color)
Passes appropriate arguments to SetLayer.
void SetHiglightLayer (guint color)
creates a Gdk::Pixbuf of color Passes appropriate arguments to SetLayer
void SetPieceLayer (const Glib::RefPtr< Gdk::Pixbuf > &piece)
Passes appropriate arguments to SetLayer.
Private Attributes
int height
Currnet width of visible image. Initializes to DEFAULT_CELL_SIZE.
int width
Currnet width of visible image. Initializes to DEFAULT_CELL_SIZE.
Visible Image Data
Data is coordinated using the enum CellLayer as indexing values
std::vector< const
Glib::RefPtr< Gdk::Pixbuf > * > layers
vector of pointers to References to PixBufs (for easy image switching) Original references are stored by ChessGuiImages.
Glib::RefPtr< Gdk::Pixbuf > highlight
ChessGuiImages does not store highligts (too many possibilities) so the cell does.
std::vector< bool > layer_visible
layer_visible[i] stores weather the PixBuf at layers[i] should be drawn
std::vector< signed int > layer_alpha
opacity of layer i 0(transparent)-255(opaque)
Friends
class ChessGuiBoard
Detailed Description
Provides functionality for drawing layered images to each cell of a ChessGuiBoard.
Note:
Depends heavily on cs240chess.glade
Constructor & Destructor Documentation
ChessGuiBoardCell::ChessGuiBoardCell (BaseObjectType * cobject, const Glib::RefPtr< Gnome::Glade::Xml > & refGlade)
This format of constructor is necessary for this constructor to be automatically used by the Glade::Xml::get_derived_widget() function.
See "Glade File"
Parameters:
cobject initialize Gtk::Window
refGlade is generated beforehand using libglademm
References DEFAULT_CELL_SIZE, height, layer_alpha, layer_visible, layers, MAX_LAYER, and width.
ChessGuiBoardCell::~ChessGuiBoardCell () [private]
Member Function Documentation
void ChessGuiBoardCell::SetBackGroundLayer (const Glib::RefPtr< Gdk::Pixbuf > & bg) [private]
Passes appropriate arguments to SetLayer.
References BACK_GRND_LAYER, and SetLayer().
Referenced by ChessGuiBoard::InitCell().
void ChessGuiBoardCell::SetHiglightLayer (guint color) [private]
creates a Gdk::Pixbuf of color Passes appropriate arguments to SetLayer
Parameters:
color predefined colors here
References BITS_PER_SAMPLE, DEFAULT_CELL_SIZE, highlight, HIGHLIGHT_LAYER, SetLayer(), and TILE_ALPHA.
Referenced by ChessGuiBoard::HighlightSquare().
void ChessGuiBoardCell::SetLayer (const Glib::RefPtr< Gdk::Pixbuf > & pix, CellLayer layer, bool visible = true, signed int alpha = 255) [private]
Parameters:
pix a Gdk::Pixbuf that will be set at layer
layer as defined by CellLayer
visible whether this layer should be shown, default = true
alpha level of transparency 0-255 of this layer (255 is opaque)
References layer_alpha, layer_visible, layers, and MAX_LAYER.
Referenced by SetBackGroundLayer(), SetHiglightLayer(), SetPieceLayer(), and SetTileLayer().
void ChessGuiBoardCell::SetLayerVisible (CellLayer layer, bool visible = true) [private]
sets wheter a layer should be drawn or not
Parameters:
layer layer to be set
visible wether the layer will be drawn to Image on the next call to UpdateImage
References layer_visible.
Referenced by ChessGuiBoard::ClearPiece(), and ChessGuiBoard::UnHighlightSquare().
void ChessGuiBoardCell::SetPieceLayer (const Glib::RefPtr< Gdk::Pixbuf > & piece) [private]
Passes appropriate arguments to SetLayer.
References PIECE_LAYER, and SetLayer().
Referenced by ChessGuiBoard::PlacePiece().
void ChessGuiBoardCell::SetTileLayer (const Glib::RefPtr< Gdk::Pixbuf > & color) [private]
Passes appropriate arguments to SetLayer.
References SetLayer(), TILE_ALPHA, and TILE_LAYER.
Referenced by ChessGuiBoard::InitCell().
void ChessGuiBoardCell::UpdateImage () [private]
Draw all visible layers to image.
References BACK_GRND_LAYER, CELL_PAD, ChessGuiImages::GetErrorImage(), ChessGuiImages::GetImage(), height, layer_alpha, layer_visible, layers, MAX_LAYER, NO_IMAGE, and width.
Referenced by ChessGuiBoard::ClearPiece(), ChessGuiBoard::HighlightSquare(), ChessGuiBoard::InitCell(), ChessGuiBoard::PlacePiece(), ChessGuiBoard::RefreshBoard(), ChessGuiBoard::ResizeBoard(), and ChessGuiBoard::UnHighlightSquare().
Friends And Related Function Documentation
friend class ChessGuiBoard [friend]
Member Data Documentation
int ChessGuiBoardCell::height [private]
Currnet width of visible image. Initializes to DEFAULT_CELL_SIZE.
Referenced by ChessGuiBoardCell(), ChessGuiBoard::ResizeBoard(), and UpdateImage().
Glib::RefPtr<Gdk::Pixbuf> ChessGuiBoardCell::highlight [private]
ChessGuiImages does not store highligts (too many possibilities) so the cell does.
Referenced by SetHiglightLayer().
std::vector<signed int> ChessGuiBoardCell::layer_alpha [private]
opacity of layer i 0(transparent)-255(opaque)
Referenced by ChessGuiBoardCell(), SetLayer(), and UpdateImage().
std::vector<bool> ChessGuiBoardCell::layer_visible [private]
layer_visible[i] stores weather the PixBuf at layers[i] should be drawn
Referenced by ChessGuiBoardCell(), SetLayer(), SetLayerVisible(), and UpdateImage().
std::vector<const Glib::RefPtr<Gdk::Pixbuf> * > ChessGuiBoardCell::layers [private]
vector of pointers to References to PixBufs (for easy image switching) Original references are stored by ChessGuiImages.
When the images in ChessGuiImages are modified and the cell is refreshed, the Image will be automatically updated. Memory is freed by RefPtr
Referenced by ChessGuiBoardCell(), SetLayer(), and UpdateImage().
int ChessGuiBoardCell::width [private]
Currnet width of visible image. Initializes to DEFAULT_CELL_SIZE.
Referenced by ChessGuiBoardCell(), ChessGuiBoard::ResizeBoard(), and UpdateImage().
The documentation for this class was generated from the following files:
ChessGuiBoardCell.h
ChessGuiBoardCell.cpp