CS240Project: ChessGuiImages Class Reference
ChessGuiImages Class Reference
Provides a static repository for Gdk::Pixbuf that are used throughout the GUI.
#include <ChessGuiImages.h>
Static Public Member Functions
static const Glib::RefPtr
< Gdk::Pixbuf > & GetErrorImage ()
static const Glib::RefPtr
< Gdk::Pixbuf > & GetImage (ImageName image)
static bool isLoaded (ImageName image)
static void LoadDefaultImages ()
Loads images using the default names (SetDefaultFileNames) and a default path set at compile time.
static bool Loaded ()
static void LoadImage (const std::string &path, ImageName image)
Loads individual image with file located at path.
static void LoadImages (const std::string &path)
looks in directory defined by path for images following default naming (SetDefaultFileNames)
Private Member Functions
ChessGuiImages ()
this class has no individual instantiation
Static Private Member Functions
static void CombinePathAndFileName (std::string path)
Prepends path to the contents of imagePaths Does not modify any element of imagePaths that is empty (no default image/image desired)
static void LoadImageFiles ()
Attempts to load the values of imagePaths as Gdk::Pixbufs into images, matching indexes.
static void SetDefaultFileNames ()
loads default filenames into imagePaths
static void SetTilePatternImages ()
Checks to see if a tile image was provided, if not, sets the tile to use BLACK_SQUARE or WHITE_SQUARE as needed.
Static Private Attributes
static Glib::RefPtr< Gdk::Pixbuf > error
Default Image Not Found/Error icon Image is compiled in.
static std::vector< std::string > imagePaths
vector holding the paths to the source file for each image
static std::vector
< Glib::RefPtr< Gdk::Pixbuf > > images
Static repository of images.
static bool loaded = false
status variable indicating if the last load failed or succeeded
Detailed Description
Provides a static repository for Gdk::Pixbuf that are used throughout the GUI.
Allows for dynamically loading and switching images during the runtime of the program. Allows the finished chess program to be run from any directory, and not only the one it was compiled in
Constructor & Destructor Documentation
ChessGuiImages::ChessGuiImages () [private]
this class has no individual instantiation
Member Function Documentation
void ChessGuiImages::CombinePathAndFileName (std::string path) [static, private]
Prepends path to the contents of imagePaths Does not modify any element of imagePaths that is empty (no default image/image desired)
References imagePaths, NO_IMAGE, and NUM_IMAGE_NAMES.
Referenced by LoadImages().
const Glib::RefPtr< Gdk::Pixbuf > & ChessGuiImages::GetErrorImage () [static]
Returns:
a reference to the default error image
References error, GetImage(), and NO_IMAGE.
Referenced by ChessGuiBoardCell::UpdateImage().
const Glib::RefPtr< Gdk::Pixbuf > & ChessGuiImages::GetImage (ImageName image) [static]
Returns:
a referemce to the Pixbuf stored matching the identifier images
Parameters:
image The ImageName of the desired image
References images, LoadDefaultImages(), NO_IMAGE, and NUM_IMAGE_NAMES.
Referenced by GetErrorImage(), ChessGuiBoard::InitCell(), ChessGui::on_About(), ChessGuiBoard::PlacePiece(), and ChessGuiBoardCell::UpdateImage().
bool ChessGuiImages::isLoaded (ImageName image) [static]
Returns:
true if image has been loaded and is not equal to NO_IMAGE
References images, loaded, and NO_IMAGE.
void ChessGuiImages::LoadDefaultImages () [static]
Loads images using the default names (SetDefaultFileNames) and a default path set at compile time.
References LoadImages().
Referenced by ChessGui::ChessGui(), GetImage(), and SetTilePatternImages().
bool ChessGuiImages::Loaded () [static]
Returns:
loaded
References loaded.
Referenced by ChessGui::ChessGui(), and ChessGui::on_LoadImages().
void ChessGuiImages::LoadImage (const std::string & path, ImageName image) [static]
Loads individual image with file located at path.
If the image cannot be loaded, it is set to be the same as ImageName::NO_IMAGE
Parameters:
path complete path, including filename, to the image
image The ImageName that will be associated with the image
References imagePaths, images, NO_IMAGE, and NUM_IMAGE_NAMES.
Referenced by LoadImageFiles().
void ChessGuiImages::LoadImageFiles () [static, private]
Attempts to load the values of imagePaths as Gdk::Pixbufs into images, matching indexes.
References BITS_PER_SAMPLE, CLEAR_SQUARE, DEFAULT_CELL_SIZE, imagePaths, images, loaded, LoadImage(), NO_IMAGE, NUM_IMAGE_NAMES, and SetTilePatternImages().
Referenced by LoadImages().
void ChessGuiImages::LoadImages (const std::string & path) [static]
looks in directory defined by path for images following default naming (SetDefaultFileNames)
Parameters:
path path to the directory containing the image files
References CombinePathAndFileName(), error, ImageError, LoadImageFiles(), and SetDefaultFileNames().
Referenced by LoadDefaultImages(), main(), and ChessGui::on_LoadImages().
void ChessGuiImages::SetDefaultFileNames () [static, private]
loads default filenames into imagePaths
References B_BISHOP, B_KING, B_KNIGHT, B_PAWN, B_QUEEN, B_ROOK, BACK_GRND, BLACK_TILE, imagePaths, NO_IMAGE, NUM_IMAGE_NAMES, W_BISHOP, W_KING, W_KNIGHT, W_PAWN, W_QUEEN, W_ROOK, and WHITE_TILE.
Referenced by LoadImages().
void ChessGuiImages::SetTilePatternImages () [static, private]
Checks to see if a tile image was provided, if not, sets the tile to use BLACK_SQUARE or WHITE_SQUARE as needed.
References BACK_GRND, BLACK_SQUARE, BLACK_TILE, DEFAULT_CELL_SIZE, images, LoadDefaultImages(), NO_IMAGE, NUM_IMAGE_NAMES, WHITE_SQUARE, and WHITE_TILE.
Referenced by LoadImageFiles().
Member Data Documentation
Glib::RefPtr< Gdk::Pixbuf > ChessGuiImages::error [static, private]
Default Image Not Found/Error icon Image is compiled in.
Referenced by GetErrorImage(), and LoadImages().
std::vector< std::string > ChessGuiImages::imagePaths [static, private]
vector holding the paths to the source file for each image
Referenced by CombinePathAndFileName(), LoadImage(), LoadImageFiles(), and SetDefaultFileNames().
std::vector< Glib::RefPtr< Gdk::Pixbuf > > ChessGuiImages::images [static, private]
Static repository of images.
Indexed using ImageName index NO_IMAGE always contains a transparent pixubf square
Referenced by GetImage(), isLoaded(), LoadImage(), LoadImageFiles(), and SetTilePatternImages().
bool ChessGuiImages::loaded = false [static, private]
status variable indicating if the last load failed or succeeded
Referenced by isLoaded(), Loaded(), and LoadImageFiles().
The documentation for this class was generated from the following files:
ChessGuiImages.h
ChessGuiImages.cpp