CS240Project: MoveRecord Class Reference
MoveRecord Class Reference
#include <MoveHistory.h>
Public Member Functions
Cell * GetDestCell ()
Piece * GetDisplacedPiece ()
Cell * GetHomeCell ()
Piece * GetMovedPiece ()
MoveRecord (Piece *piece, Cell *destCell)
Private Attributes
Cell * destCell
Piece * displacedPiece
Cell * homeCell
Piece * movedPiece
Constructor & Destructor Documentation
MoveRecord::MoveRecord (Piece * piece, Cell * destCell) [inline]
References destCell, displacedPiece, Piece::GetCell(), Cell::GetPiece(), homeCell, and movedPiece.
Member Function Documentation
Cell* MoveRecord::GetDestCell () [inline]
References destCell.
Referenced by ChessGame::UndoMove().
Piece* MoveRecord::GetDisplacedPiece () [inline]
References displacedPiece.
Referenced by ChessGame::UndoMove().
Cell* MoveRecord::GetHomeCell () [inline]
References homeCell.
Referenced by ChessGame::UndoMove().
Piece* MoveRecord::GetMovedPiece () [inline]
References movedPiece.
Referenced by ChessGame::UndoMove().
Member Data Documentation
Cell* MoveRecord::destCell [private]
Referenced by GetDestCell(), and MoveRecord().
Piece* MoveRecord::displacedPiece [private]
Referenced by GetDisplacedPiece(), and MoveRecord().
Cell* MoveRecord::homeCell [private]
Referenced by GetHomeCell(), and MoveRecord().
Piece* MoveRecord::movedPiece [private]
Referenced by GetMovedPiece(), and MoveRecord().
The documentation for this class was generated from the following file:
MoveHistory.h