CS240Project: ChessGame Class Reference
ChessGame Class Reference
Main interface for the backend implementation of the chess game.
#include <ChessGame.h>
Public Member Functions
bool CellHasCurrentPlayersPiece (Cell *cell)
ChessGame ()
Allocates a Board, a collection of Pieces, an empty Piece, and a PrisonCell on the heap.
std::set< Cell * > * GetValidMoves (Piece *piece)
Returns a new set of valid cells we can move to, based on whether those moves will result in the mover going into check.
bool IsValidMove (Piece *piece, Cell *destCell)
MoveRecord * Move (Piece *piece, Cell *destCell)
Moves piece to destCell.
bool MoveEndsUpInCheck (Piece *piece, Cell *cell, PieceColor playersColor)
bool PlayerInCheck (PieceColor playersColor)
Checks if this player is in check.
bool PlayerInCheckMate (PieceColor playersColor)
MoveRecord * PopMostRecentMoveRecord ()
void UndoMove (MoveRecord *record)
~ChessGame ()
Calls destructors on each heap-allocated member.
Getters (to be used by ChessControllerImpl)
Cell * GetCell (int row, int col)
Returns a pointer to the Cell of the respective row and column.
Piece * GetPiece (int row, int col)
Returns a pointer to the Piece held in the respective row and column.
Pieces * GetPieces ()
PieceColor GetCurrentPlayersColor ()
Private Attributes
Board * board
PieceColor currentPlayersColor
MoveHistory * moveHistory
Pieces * pieces
Detailed Description
Main interface for the backend implementation of the chess game.
This is the main interface for the backend implementation of the chess game and is meant to be used by ChessControllerImpl
Constructor & Destructor Documentation
ChessGame::ChessGame ()
Allocates a Board, a collection of Pieces, an empty Piece, and a PrisonCell on the heap.
References Board::BindCellsToPieces(), board, currentPlayersColor, moveHistory, pieces, and WHITE.
ChessGame::~ChessGame ()
Calls destructors on each heap-allocated member.
References board, moveHistory, and pieces.
Member Function Documentation
bool ChessGame::CellHasCurrentPlayersPiece (Cell * cell)
Returns:
true if cell contains a piece of the player whose turn it is
References currentPlayersColor, Piece::GetColor(), and Cell::GetPiece().
Cell * ChessGame::GetCell (int row, int col)
Returns a pointer to the Cell of the respective row and column.
Parameters:
row and
col correspond to those used in ChessController
References board, and Board::GetCell().
Referenced by ChessControllerImpl::on_CellSelected().
PieceColor ChessGame::GetCurrentPlayersColor ()
References currentPlayersColor.
Referenced by ChessControllerImpl::on_CellSelected().
Piece * ChessGame::GetPiece (int row, int col)
Returns a pointer to the Piece held in the respective row and column.
Parameters:
row and
col correspond to those used in ChessController
References board, DbgMsg, Board::GetCell(), and Cell::GetPiece().
Referenced by PlayerInCheckMate(), and ChessControllerImpl::UpdateView().
Pieces * ChessGame::GetPieces ()
References pieces.
std::set< Cell * > * ChessGame::GetValidMoves (Piece * piece)
Returns a new set of valid cells we can move to, based on whether those moves will result in the mover going into check.
References currentPlayersColor, Piece::GetValidMoves(), and MoveEndsUpInCheck().
Referenced by ChessControllerImpl::HighlightValidMoves(), IsValidMove(), and PlayerInCheckMate().
bool ChessGame::IsValidMove (Piece * piece, Cell * destCell)
References GetValidMoves().
Referenced by ChessControllerImpl::on_CellSelected().
MoveRecord * ChessGame::Move (Piece * piece, Cell * destCell)
Moves piece to destCell.
Parameters:
piece
destCell
Todo:
have Move return a MoveRecord*
References Piece::BindToCell(), Cell::BindToPiece(), BLACK, currentPlayersColor, Piece::GetCell(), Cell::GetPiece(), and WHITE.
Referenced by MoveEndsUpInCheck(), and ChessControllerImpl::on_CellSelected().
bool ChessGame::MoveEndsUpInCheck (Piece * piece, Cell * cell, PieceColor playersColor)
Returns:
true if the specified move will result in check for the given player
References Move(), PlayerInCheck(), and UndoMove().
Referenced by GetValidMoves().
bool ChessGame::PlayerInCheck (PieceColor playersColor)
Checks if this player is in check.
References BLACK, board, Pieces::gBlackKing(), Piece::GetCell(), Board::GetCell(), Piece::GetColor(), Cell::GetPiece(), Pieces::gWhiteKing(), pieces, Piece::ValidMovesContains(), and WHITE.
Referenced by MoveEndsUpInCheck(), and ChessControllerImpl::on_CellSelected().
bool ChessGame::PlayerInCheckMate (PieceColor playersColor)
References GetPiece(), and GetValidMoves().
Referenced by ChessControllerImpl::on_CellSelected().
MoveRecord * ChessGame::PopMostRecentMoveRecord ()
References moveHistory, and MoveHistory::PopMostRecentMoveRecord().
void ChessGame::UndoMove (MoveRecord * record)
References Piece::BindToCell(), Cell::BindToPiece(), BLACK, currentPlayersColor, MoveRecord::GetDestCell(), MoveRecord::GetDisplacedPiece(), MoveRecord::GetHomeCell(), MoveRecord::GetMovedPiece(), and WHITE.
Referenced by MoveEndsUpInCheck().
Member Data Documentation
Board* ChessGame::board [private]
Referenced by ChessGame(), GetCell(), GetPiece(), PlayerInCheck(), and ~ChessGame().
PieceColor ChessGame::currentPlayersColor [private]
Referenced by CellHasCurrentPlayersPiece(), ChessGame(), GetCurrentPlayersColor(), GetValidMoves(), Move(), and UndoMove().
MoveHistory* ChessGame::moveHistory [private]
Referenced by ChessGame(), PopMostRecentMoveRecord(), and ~ChessGame().
Pieces* ChessGame::pieces [private]
Referenced by ChessGame(), GetPieces(), PlayerInCheck(), and ~ChessGame().
The documentation for this class was generated from the following files:
ChessGame.h
ChessGame.cpp