CS240Project: Cell Class Reference
Cell Class Reference
An interface for the Cell class that holds a piece (real or empty).
#include <Cell.h>
Public Member Functions
Cell ()
Cell (Board *board, int row, int col)
~Cell ()
Setters
void BindToPiece (Piece *piece)
Getters
Piece * GetPiece ()
int GetRow ()
int GetCol ()
Directional Methods
These return the adjacent cell in the respective direction, or NULL if that cell doesn't exist.
Cell * FdLeft (PieceColor color)
Cell * Fd (PieceColor color)
Cell * FdRight (PieceColor color)
Cell * Left (PieceColor color)
Cell * Right (PieceColor color)
Cell * BkLeft (PieceColor color)
Cell * Bk (PieceColor color)
Cell * BkRight (PieceColor color)
Protected Attributes
Board * board
int col
Piece * piece
int row
Detailed Description
An interface for the Cell class that holds a piece (real or empty).
This class also has directional functions for adjacent cells.
Constructor & Destructor Documentation
Cell::Cell ()
References board, col, piece, and row.
Cell::Cell (Board * board, int row, int col)
Parameters:
piece is the Piece object to which this Cell will point.
References piece.
Cell::~Cell ()
Note:
This dtor does nothing special, as Cell allocates nothing on the heap.
Member Function Documentation
void Cell::BindToPiece (Piece * piece)
References piece.
Referenced by Board::BindCellsToPieces(), ChessGame::Move(), and ChessGame::UndoMove().
Cell * Cell::Bk (PieceColor color)
References board, col, Board::GetCell(), row, and WHITE.
Referenced by BkLeft(), BkRight(), Rook::UpdateValidMoves(), Queen::UpdateValidMoves(), Knight::UpdateValidMoves(), and King::UpdateValidMoves().
Cell * Cell::BkLeft (PieceColor color)
References Bk(), and Left().
Referenced by Queen::UpdateValidMoves(), Knight::UpdateValidMoves(), King::UpdateValidMoves(), and Bishop::UpdateValidMoves().
Cell * Cell::BkRight (PieceColor color)
References Bk(), and Right().
Referenced by Queen::UpdateValidMoves(), Knight::UpdateValidMoves(), King::UpdateValidMoves(), and Bishop::UpdateValidMoves().
Cell * Cell::Fd (PieceColor color)
References board, col, Board::GetCell(), row, and WHITE.
Referenced by FdLeft(), FdRight(), Rook::UpdateValidMoves(), Queen::UpdateValidMoves(), Pawn::UpdateValidMoves(), Knight::UpdateValidMoves(), and King::UpdateValidMoves().
Cell * Cell::FdLeft (PieceColor color)
References Fd(), and Left().
Referenced by Queen::UpdateValidMoves(), Pawn::UpdateValidMoves(), Knight::UpdateValidMoves(), King::UpdateValidMoves(), and Bishop::UpdateValidMoves().
Cell * Cell::FdRight (PieceColor color)
References Fd(), and Right().
Referenced by Queen::UpdateValidMoves(), Pawn::UpdateValidMoves(), Knight::UpdateValidMoves(), King::UpdateValidMoves(), and Bishop::UpdateValidMoves().
int Cell::GetCol ()
References col.
Referenced by Piece::GetCol().
Piece * Cell::GetPiece ()
References piece.
Referenced by ChessGame::CellHasCurrentPlayersPiece(), ChessGame::GetPiece(), ChessGame::Move(), MoveRecord::MoveRecord(), ChessControllerImpl::on_CellSelected(), ChessGame::PlayerInCheck(), Rook::UpdateValidMoves(), Queen::UpdateValidMoves(), Pawn::UpdateValidMoves(), Knight::UpdateValidMoves(), King::UpdateValidMoves(), and Bishop::UpdateValidMoves().
int Cell::GetRow ()
References row.
Referenced by Piece::GetRow(), and Pawn::UpdateValidMoves().
Cell * Cell::Left (PieceColor color)
References board, col, Board::GetCell(), row, and WHITE.
Referenced by BkLeft(), FdLeft(), Rook::UpdateValidMoves(), Queen::UpdateValidMoves(), Knight::UpdateValidMoves(), and King::UpdateValidMoves().
Cell * Cell::Right (PieceColor color)
References board, col, Board::GetCell(), row, and WHITE.
Referenced by BkRight(), FdRight(), Rook::UpdateValidMoves(), Queen::UpdateValidMoves(), Knight::UpdateValidMoves(), and King::UpdateValidMoves().
Member Data Documentation
Board* Cell::board [protected]
Referenced by Bk(), Cell(), Fd(), Left(), and Right().
int Cell::col [protected]
Referenced by Bk(), Cell(), Fd(), GetCol(), Left(), and Right().
Piece* Cell::piece [protected]
Referenced by BindToPiece(), Cell(), and GetPiece().
int Cell::row [protected]
Referenced by Bk(), Cell(), Fd(), GetRow(), Left(), and Right().
The documentation for this class was generated from the following files:
Cell.h
Cell.cpp