CS240Project: Chess Class Reference
Chess Class Reference
This class is the main interface between the Students code and the provided GUI.
#include <Chess.h>
Public Member Functions
Chess (std::string gladefile)
virtual void ClearMessageArea ()
Clear all data in the Message Area.
virtual void ClearPiece (signed int row, signed int col)
virtual void HighlightSquare (signed int row, signed int col, guint32 color)
virtual void PlacePiece (signed int row, signed int col, ImageName piece)
void run (Gtk::Main &app)
allows Gtk::Main to handle showing and hiding the window on exit
virtual std::string SelectLoadFile ()
Opens a Gtk::FileChooserDialog in the FILE_OPEN mode.
virtual std::string SelectSaveFile ()
Opens a Gtk::FileChooserDialog in the FILE_SAVE mode.
virtual void SetBottomLabel (const std::string &text)
Place text in area below the chess board.
virtual void SetController (ChessController *controller)
Set the ChessController that this ChessView will pass all of its inputs to.
virtual void SetStatusBar (const std::string &status)
Set text in the Statusbar located at the bottom of the ChessGui.
virtual void SetTimeoutMilliseconds (int milliseconds)
virtual void SetTopLabel (const std::string &text)
Place text in area above the chess board.
virtual void UnHighlightSquare (signed int row, signed int col)
virtual void WriteMessageArea (const std::string &message)
Write a string to the Message Area.
~Chess ()
Student Implemented Functions
void on_CellSelected (int row, int col, int button)
Connected to (activated by) ChessGui::signal_cell_selected()
void on_NewGame ()
Connected to (activated by) ChessGui::signal_new_selected()
void on_SaveGame ()
Connected to (activated by) ChessGui::signal_save_selected()
void on_SaveGameAs ()
Connected to (activated by) ChessGui::signal_save_as_selected()
void on_LoadGame ()
Connected to (activated by) ChessGui::signal_load_selected()
void on_UndoMove ()
Connected to (activated by) ChessGui::signal_undo_selected()
void on_QuitGame ()
Connected to (activated by) ChessGui::signal_quit_selected()
bool on_TimerEvent ()
This method will be called every tenth of a second.
void on_DragStart (int row, int col)
bool on_DragEnd (int row, int col)
Private Member Functions
void CleanupChessGui ()
void InitializeChessGui (const std::string &gladefile)
void InitializeTimer ()
Private Attributes
ChessController * controller
ChessGui * gui
Access to the user interface.
guint logId
Log-id (for memory management)
int timeoutMilliseconds
Detailed Description
This class is the main interface between the Students code and the provided GUI.
The Student will implement each of the signal handlers found in this class. It is permitted to add member data and functions. The constructor and the destructor should be finished to suit the needs of the student.
Note:
Access the convenience functions using the pointer Chess::gui
Constructor & Destructor Documentation
Chess::Chess (std::string gladefile)
Parameters:
gladefile See "Glade File"
argc The number of commandline arguments passed to this program.
argv Pointers to the commandline argument strings passed to this program.
References controller, InitializeChessGui(), and timeoutMilliseconds.
Chess::~Chess ()
References CleanupChessGui().
Member Function Documentation
void Chess::CleanupChessGui () [private]
References gui, and logId.
Referenced by ~Chess().
void Chess::InitializeChessGui (const std::string & gladefile) [private]
References gui, log_handler(), logId, on_CellSelected(), on_DragEnd(), on_DragStart(), on_LoadGame(), on_NewGame(), on_QuitGame(), on_SaveGame(), on_SaveGameAs(), on_UndoMove(), ChessGui::signal_cell_selected(), ChessGui::signal_drag_end(), ChessGui::signal_drag_start(), ChessGui::signal_load(), ChessGui::signal_new(), ChessGui::signal_quit(), ChessGui::signal_save(), ChessGui::signal_save_as(), and ChessGui::signal_undo().
Referenced by Chess().
void Chess::InitializeTimer () [private]
References on_TimerEvent(), and timeoutMilliseconds.
Referenced by run().
void Chess::on_CellSelected (int row, int col, int button)
Connected to (activated by) ChessGui::signal_cell_selected()
Parameters:
row 1-8, top to bottom
col 1-8, left to right
button 1=left mouse button, 2=middle mouse button, 3=right mouse button
References controller, and ChessController::on_CellSelected().
Referenced by InitializeChessGui().
bool Chess::on_DragEnd (int row, int col)
Parameters:
row where drag ended
col where drag ended
Returns:
true if the drag resulted in a successful drop
References controller, and ChessController::on_DragEnd().
Referenced by InitializeChessGui().
void Chess::on_DragStart (int row, int col)
Parameters:
row where drag began
col where drag began
References controller, and ChessController::on_DragStart().
Referenced by InitializeChessGui().
void Chess::on_LoadGame ()
Connected to (activated by) ChessGui::signal_load_selected()
References controller, and ChessController::on_LoadGame().
Referenced by InitializeChessGui().
void Chess::on_NewGame ()
Connected to (activated by) ChessGui::signal_new_selected()
References controller, and ChessController::on_NewGame().
Referenced by InitializeChessGui(), and run().
void Chess::on_QuitGame ()
Connected to (activated by) ChessGui::signal_quit_selected()
References controller, and ChessController::on_QuitGame().
Referenced by InitializeChessGui().
void Chess::on_SaveGame ()
Connected to (activated by) ChessGui::signal_save_selected()
References controller, and ChessController::on_SaveGame().
Referenced by InitializeChessGui().
void Chess::on_SaveGameAs ()
Connected to (activated by) ChessGui::signal_save_as_selected()
References controller, and ChessController::on_SaveGameAs().
Referenced by InitializeChessGui().
bool Chess::on_TimerEvent ()
This method will be called every tenth of a second.
References controller, and ChessController::on_TimerEvent().
Referenced by InitializeTimer().
void Chess::on_UndoMove ()
Connected to (activated by) ChessGui::signal_undo_selected()
References controller, and ChessController::on_UndoMove().
Referenced by InitializeChessGui().
void Chess::run (Gtk::Main & app)
allows Gtk::Main to handle showing and hiding the window on exit
References gui, InitializeTimer(), and on_NewGame().
Referenced by main().
void Chess::SetController (ChessController * controller) [virtual]
Set the ChessController that this ChessView will pass all of its inputs to.
Implements ChessView.
References controller.
Referenced by main().
void Chess::SetTimeoutMilliseconds (int milliseconds) [virtual]
References timeoutMilliseconds.
Member Data Documentation
ChessController* Chess::controller [private]
Referenced by Chess(), on_CellSelected(), on_DragEnd(), on_DragStart(), on_LoadGame(), on_NewGame(), on_QuitGame(), on_SaveGame(), on_SaveGameAs(), on_TimerEvent(), on_UndoMove(), and SetController().
ChessGui* Chess::gui [private]
Access to the user interface.
Referenced by CleanupChessGui(), ClearMessageArea(), ClearPiece(), HighlightSquare(), InitializeChessGui(), PlacePiece(), run(), SelectLoadFile(), SelectSaveFile(), SetBottomLabel(), SetStatusBar(), SetTopLabel(), UnHighlightSquare(), and WriteMessageArea().
guint Chess::logId [private]
Log-id (for memory management)
Referenced by CleanupChessGui(), and InitializeChessGui().
int Chess::timeoutMilliseconds [private]
Referenced by Chess(), InitializeTimer(), and SetTimeoutMilliseconds().
The documentation for this class was generated from the following files:
Chess.h
Chess.cpp