CS240Project: ChessGui Class Reference
ChessGui Class Reference
Toplevel Widget of the CS240 Chess Project.
#include <ChessGui.h>
Public Member Functions
ChessGui (BaseObjectType *cobject, const Glib::RefPtr< Gnome::Glade::Xml > &chXml)
This format of constructor is necessary for this constructor to be automatically used by the Glade::Xml::get_derived_widget() function.
bool on_main_delete_event (GdkEventAny *event)
Overides Gtk::Window::on_main_delete_event Use if needed for last minute cleanup.
~ChessGui ()
Glade::Xml handles destroying Widgets.
Chess Gui Convenience Functions
void SetTopLabel (const std::string &text)
Place text in area above the chess board.
void SetBottomLabel (const std::string &text)
Place text in area below the chess board.
void ClearMessageArea ()
Clear all data in the Message Area.
void WriteMessageArea (const std::string &message)
Write a string to the Message Area.
void SetStatusBar (const std::string &status)
Set text in the Statusbar located at the bottom of the ChessGui.
std::string SelectSaveFile ()
Opens a Gtk::FileChooserDialog in the FILE_SAVE mode.
std::string SelectLoadFile ()
Opens a Gtk::FileChooserDialog in the FILE_OPEN mode.
void HighlightSquare (signed int row, signed int col, guint32 color)
void UnHighlightSquare (signed int row, signed int col)
void PlacePiece (signed int row, signed int col, ImageName piece)
void ClearPiece (signed int row, signed int col)
Signal Accessor Functions
sigc::signal< void, int, int, int > signal_cell_selected ()
emited when a butten is pressed over a square
sigc::signal< void > signal_new ()
Emited when New Game is selected.
sigc::signal< void > signal_save ()
Emited when Save Game is selected.
sigc::signal< void > signal_save_as ()
Emited when Save Game As is selected.
sigc::signal< void > signal_load ()
Emited when Load Game is selected.
sigc::signal< void > signal_undo ()
Emited when Undo Move is selected.
sigc::signal< void > signal_quit ()
Emited when Quit Game is selected.
sigc::signal< void, int, int > signal_drag_start ()
emited when button 1 is pressed, held, and then the mouse is moved
sigc::signal< bool, int, int > signal_drag_end ()
emited after a drag has been initiated and the button has been released
Private Member Functions
Initialization sub-functions
void ConnectSignals ()
void ConnectMenuSignals ()
void ConnectToolBarSignals ()
Internal Signal Handlers
void on_UndoMove ()
void on_NewGame ()
void on_LoadGame ()
void on_SaveGame ()
void on_SaveGameAs ()
void on_LoadImages ()
void on_Quit ()
void on_HideMessages ()
void on_ClearMessages ()
void on_About ()
void on_ToggleToolbarView ()
Private Attributes
Glib::RefPtr< Gnome::Glade::Xml > chessXml
See "Glade File" .
int messageAreaLastPosition
contains position of hpane seperator before last call to HideMessages
widget access variables
allow for quick access to parts of chessXml.
Memory managed by Glade::Xml structure.
Gtk::Statusbar * statusbar
Gtk::TextView * messageArea
Gtk::ScrolledWindow * messageWindow
Gtk::Label * top
Gtk::Label * bottom
ChessGuiBoard * board
signals
sigc::signal< void, int, int, int > cellSelectSignal
sigc::signal< void > actionNewSignal
sigc::signal< void > actionSaveSignal
sigc::signal< void > actionSaveAsSignal
sigc::signal< void > actionLoadSignal
sigc::signal< void > actionUndoSignal
sigc::signal< void > actionQuitSignal
Detailed Description
Toplevel Widget of the CS240 Chess Project.
Signals emitted by this class will be handled by the students in the Chess class.
The exact look and feel of the window depends on the file ///See ""
Constructor & Destructor Documentation
ChessGui::ChessGui (BaseObjectType * cobject, const Glib::RefPtr< Gnome::Glade::Xml > & chXml)
This format of constructor is necessary for this constructor to be automatically used by the Glade::Xml::get_derived_widget() function.
See "Glade File"
Parameters:
cobject initialize Gtk::Window
chXml is generated beforehand using libglademm
depends on cs240chess.glade
References board, bottom, chessXml, ConnectSignals(), ChessGuiImages::LoadDefaultImages(), ChessGuiImages::Loaded(), messageArea, messageWindow, statusbar, and top.
ChessGui::~ChessGui ()
Glade::Xml handles destroying Widgets.
References board, bottom, messageArea, statusbar, and top.
Member Function Documentation
void ChessGui::ConnectMenuSignals () [private]
depends on cs240chess.glade
References chessXml, on_About(), on_ClearMessages(), on_HideMessages(), on_LoadGame(), on_LoadImages(), on_NewGame(), on_Quit(), on_SaveGame(), on_SaveGameAs(), on_ToggleToolbarView(), and on_UndoMove().
Referenced by ConnectSignals().
void ChessGui::ConnectSignals () [private]
References ConnectMenuSignals(), ConnectToolBarSignals(), and on_main_delete_event().
Referenced by ChessGui().
void ChessGui::ConnectToolBarSignals () [private]
depends on cs240chess.glade
References chessXml, on_LoadGame(), on_NewGame(), on_Quit(), on_SaveGame(), and on_UndoMove().
Referenced by ConnectSignals().
void ChessGui::on_About () [private]
References ChessGuiImages::GetImage(), and W_KING.
Referenced by ConnectMenuSignals().
void ChessGui::on_ClearMessages () [private]
References ClearMessageArea().
Referenced by ConnectMenuSignals().
void ChessGui::on_HideMessages () [private]
retrieves the Hpaned widget from chessXml
If the position property of the HPaned is not its max value,
it's current position is saved and then it is hidden.
Else, it is restored to its last position
References chessXml, and messageAreaLastPosition.
Referenced by ConnectMenuSignals().
void ChessGui::on_LoadGame () [private]
References actionLoadSignal.
Referenced by ConnectMenuSignals(), and ConnectToolBarSignals().
void ChessGui::on_LoadImages () [private]
Generates a Select Folder Dialog Folder selected should contain image files following the naming formated specified in ChessGuiImages::SetDefaultFileNames
References board, ChessGuiImages::Loaded(), ChessGuiImages::LoadImages(), and ChessGuiBoard::RefreshBoard().
Referenced by ConnectMenuSignals().
bool ChessGui::on_main_delete_event (GdkEventAny * event)
Overides Gtk::Window::on_main_delete_event Use if needed for last minute cleanup.
emits signal_quit to allow for gracefull exiting when the 'x' button is activated
References actionQuitSignal.
Referenced by ConnectSignals().
void ChessGui::on_NewGame () [private]
References actionNewSignal.
Referenced by ConnectMenuSignals(), and ConnectToolBarSignals().
void ChessGui::on_Quit () [private]
activates the destroy process
References actionQuitSignal.
Referenced by ConnectMenuSignals(), and ConnectToolBarSignals().
void ChessGui::on_SaveGame () [private]
References actionSaveSignal.
Referenced by ConnectMenuSignals(), and ConnectToolBarSignals().
void ChessGui::on_SaveGameAs () [private]
References actionSaveAsSignal.
Referenced by ConnectMenuSignals().
void ChessGui::on_ToggleToolbarView () [private]
References chessXml.
Referenced by ConnectMenuSignals().
void ChessGui::on_UndoMove () [private]
References actionUndoSignal.
Referenced by ConnectMenuSignals(), and ConnectToolBarSignals().
sigc::signal< void, int, int, int > ChessGui::signal_cell_selected ()
emited when a butten is pressed over a square
Note:
If the button 1 is pressed and a drag is initiated, signal will only be emitted if the drage terminates in the same square
signal handler has form void on_cell_selected(int row, int col, int button);
References board, and ChessGuiBoard::signal_cell_selected().
Referenced by Chess::InitializeChessGui().
sigc::signal< bool, int, int > ChessGui::signal_drag_end ()
emited after a drag has been initiated and the button has been released
Note:
signal handler has the form bool on_drag_end(int endRow, int endCol);
signal handler should return false if drag was invalid
References board, and ChessGuiBoard::signal_drag_end().
Referenced by Chess::InitializeChessGui().
sigc::signal< void, int, int > ChessGui::signal_drag_start ()
emited when button 1 is pressed, held, and then the mouse is moved
Note:
signal handler has the form void on_drag_start(int startRow, int endRow);
References board, and ChessGuiBoard::signal_drag_start().
Referenced by Chess::InitializeChessGui().
sigc::signal< void > ChessGui::signal_load ()
Emited when Load Game is selected.
References actionLoadSignal.
Referenced by Chess::InitializeChessGui().
sigc::signal< void > ChessGui::signal_new ()
Emited when New Game is selected.
References actionNewSignal.
Referenced by Chess::InitializeChessGui().
sigc::signal< void > ChessGui::signal_quit ()
Emited when Quit Game is selected.
References actionQuitSignal.
Referenced by Chess::InitializeChessGui().
sigc::signal< void > ChessGui::signal_save ()
Emited when Save Game is selected.
References actionSaveSignal.
Referenced by Chess::InitializeChessGui().
sigc::signal< void > ChessGui::signal_save_as ()
Emited when Save Game As is selected.
References actionSaveAsSignal.
Referenced by Chess::InitializeChessGui().
sigc::signal< void > ChessGui::signal_undo ()
Emited when Undo Move is selected.
References actionUndoSignal.
Referenced by Chess::InitializeChessGui().
Member Data Documentation
sigc::signal<void> ChessGui::actionLoadSignal [private]
Referenced by on_LoadGame(), and signal_load().
sigc::signal<void> ChessGui::actionNewSignal [private]
Referenced by on_NewGame(), and signal_new().
sigc::signal<void> ChessGui::actionQuitSignal [private]
Referenced by on_main_delete_event(), on_Quit(), and signal_quit().
sigc::signal<void> ChessGui::actionSaveAsSignal [private]
Referenced by on_SaveGameAs(), and signal_save_as().
sigc::signal<void> ChessGui::actionSaveSignal [private]
Referenced by on_SaveGame(), and signal_save().
sigc::signal<void> ChessGui::actionUndoSignal [private]
Referenced by on_UndoMove(), and signal_undo().
ChessGuiBoard* ChessGui::board [private]
Referenced by ChessGui(), ClearPiece(), HighlightSquare(), on_LoadImages(), PlacePiece(), signal_cell_selected(), signal_drag_end(), signal_drag_start(), UnHighlightSquare(), and ~ChessGui().
Gtk::Label* ChessGui::bottom [private]
Referenced by ChessGui(), SetBottomLabel(), and ~ChessGui().
sigc::signal<void, int, int, int> ChessGui::cellSelectSignal [private]
Glib::RefPtr<Gnome::Glade::Xml> ChessGui::chessXml [private]
See "Glade File" .
Referenced by ChessGui(), ConnectMenuSignals(), ConnectToolBarSignals(), on_HideMessages(), and on_ToggleToolbarView().
Gtk::TextView* ChessGui::messageArea [private]
Referenced by ChessGui(), ClearMessageArea(), WriteMessageArea(), and ~ChessGui().
int ChessGui::messageAreaLastPosition [private]
contains position of hpane seperator before last call to HideMessages
Referenced by on_HideMessages().
Gtk::ScrolledWindow* ChessGui::messageWindow [private]
Referenced by ChessGui(), and WriteMessageArea().
Gtk::Statusbar* ChessGui::statusbar [private]
Referenced by ChessGui(), SetStatusBar(), and ~ChessGui().
Gtk::Label* ChessGui::top [private]
Referenced by ChessGui(), SetTopLabel(), and ~ChessGui().
The documentation for this class was generated from the following files:
ChessGui.h
ChessGui.cpp