CS240Project: Queen Class Reference
Queen Class Reference
#include <Queen.h>
Public Member Functions
std::set< Cell * > * GetValidMoves ()
Returns a set of the cells this piece is allowed to move to.
bool ValidMovesContains (Cell *cell)
Protected Member Functions
Queen (Cell *cell)
void UpdateValidMoves ()
Update validMoves to match the state of the current board.
Constructor & Destructor Documentation
Queen::Queen (Cell * cell) [protected]
References Piece::cell, QUEEN, Piece::type, and Piece::validMoves.
Member Function Documentation
std::set< Cell * > * Queen::GetValidMoves () [virtual]
Returns a set of the cells this piece is allowed to move to.
Implements Piece.
References UpdateValidMoves(), and Piece::validMoves.
void Queen::UpdateValidMoves () [protected, virtual]
Update validMoves to match the state of the current board.
Implements Piece.
References Cell::Bk(), Cell::BkLeft(), Cell::BkRight(), Piece::cell, Piece::color, Cell::Fd(), Cell::FdLeft(), Cell::FdRight(), Piece::GetColor(), Cell::GetPiece(), Cell::Left(), Cell::Right(), and Piece::validMoves.
Referenced by GetValidMoves(), and ValidMovesContains().
bool Queen::ValidMovesContains (Cell * cell) [virtual]
Returns:
true if cell is in the set of valid moves
Implements Piece.
References UpdateValidMoves(), and Piece::validMoves.
The documentation for this class was generated from the following files:
Queen.h
Queen.cpp