CS240Project: Knight Class Reference
Knight Class Reference
#include <Knight.h>
Public Member Functions
std::set< Cell * > * GetValidMoves ()
Returns a set of the cells this piece is allowed to move to.
bool ValidMovesContains (Cell *cell)
Protected Member Functions
Knight (Cell *cell, int id)
void UpdateValidMoves ()
Update validMoves to match the state of the current board.
Constructor & Destructor Documentation
Knight::Knight (Cell * cell, int id) [protected]
References Piece::cell, Piece::id, KNIGHT, Piece::type, and Piece::validMoves.
Member Function Documentation
std::set< Cell * > * Knight::GetValidMoves () [virtual]
Returns a set of the cells this piece is allowed to move to.
Implements Piece.
References UpdateValidMoves(), and Piece::validMoves.
void Knight::UpdateValidMoves () [protected, virtual]
Update validMoves to match the state of the current board.
Implements Piece.
References Cell::Bk(), Cell::BkLeft(), Cell::BkRight(), Piece::cell, Piece::color, Cell::Fd(), Cell::FdLeft(), Cell::FdRight(), Piece::GetColor(), Cell::GetPiece(), Cell::Left(), Cell::Right(), and Piece::validMoves.
Referenced by GetValidMoves(), and ValidMovesContains().
bool Knight::ValidMovesContains (Cell * cell) [virtual]
Returns:
true if cell is in the set of valid moves
Implements Piece.
References UpdateValidMoves(), and Piece::validMoves.
The documentation for this class was generated from the following files:
Knight.h
Knight.cpp