CS240Project: ChessController Class Reference
ChessController Class Reference
#include <ChessController.h>
Public Member Functions
virtual void on_CellSelected (int row, int col, int button)=0
Indicate to the player that the user clicked on the given row and column with the mouse.
virtual bool on_DragEnd (int row, int col)=0
virtual void on_DragStart (int row, int col)=0
virtual void on_LoadGame ()=0
Handle when the user selected the load game button.
virtual void on_NewGame ()=0
Handle when the user selected the new game button.
virtual void on_QuitGame ()=0
Handle when the user selects to quit the game, either through the quit button, the close X button, or the file menu.
virtual void on_SaveGame ()=0
Handle when the user selected the save game button.
virtual void on_SaveGameAs ()=0
Handle when the user selected the save game as button.
virtual void on_TimerEvent ()=0
Handle when a timer event has been signaled.
virtual void on_UndoMove ()=0
Handle when the user selected the undo move button.
virtual void SetView (ChessView *view)=0
Set the ChessView that this ChessController will handle inputs for.
Member Function Documentation
virtual void ChessController::on_CellSelected (int row, int col, int button) [pure virtual]
Indicate to the player that the user clicked on the given row and column with the mouse.
Implemented in ChessControllerImpl.
Referenced by Chess::on_CellSelected().
virtual bool ChessController::on_DragEnd (int row, int col) [pure virtual]
Parameters:
row where drag ended
col where drag ended
Returns:
true if the drag resulted in a successful drop
Implemented in ChessControllerImpl.
Referenced by Chess::on_DragEnd().
virtual void ChessController::on_DragStart (int row, int col) [pure virtual]
Parameters:
row where drag began
col where drag began
Implemented in ChessControllerImpl.
Referenced by Chess::on_DragStart().
virtual void ChessController::on_LoadGame () [pure virtual]
Handle when the user selected the load game button.
Implemented in ChessControllerImpl.
Referenced by Chess::on_LoadGame().
virtual void ChessController::on_NewGame () [pure virtual]
Handle when the user selected the new game button.
Implemented in ChessControllerImpl.
Referenced by Chess::on_NewGame().
virtual void ChessController::on_QuitGame () [pure virtual]
Handle when the user selects to quit the game, either through the quit button, the close X button, or the file menu.
Implemented in ChessControllerImpl.
Referenced by Chess::on_QuitGame().
virtual void ChessController::on_SaveGame () [pure virtual]
Handle when the user selected the save game button.
Implemented in ChessControllerImpl.
Referenced by Chess::on_SaveGame().
virtual void ChessController::on_SaveGameAs () [pure virtual]
Handle when the user selected the save game as button.
Implemented in ChessControllerImpl.
Referenced by Chess::on_SaveGameAs().
virtual void ChessController::on_TimerEvent () [pure virtual]
Handle when a timer event has been signaled.
Implemented in ChessControllerImpl.
Referenced by Chess::on_TimerEvent().
virtual void ChessController::on_UndoMove () [pure virtual]
Handle when the user selected the undo move button.
Implemented in ChessControllerImpl.
Referenced by Chess::on_UndoMove().
virtual void ChessController::SetView (ChessView * view) [pure virtual]
Set the ChessView that this ChessController will handle inputs for.
Implemented in ChessControllerImpl.
The documentation for this class was generated from the following file:
ChessController.h