CS240Project: ChessControllerImpl Class Reference
ChessControllerImpl Class Reference
#include <ChessControllerImpl.h>
Public Member Functions
ChessControllerImpl ()
Constructor.
ChessControllerImpl (ChessGame *game)
void on_CellSelected (int row, int col, int button)
Indicate to the player that the user clicked on the given row and column with the mouse.
bool on_DragEnd (int row, int col)
void on_DragStart (int row, int col)
void on_LoadGame ()
Handle when the user selected the load game button.
void on_NewGame ()
Handle when the user selected the new game button.
void on_QuitGame ()
Handle when the user selects to quit the game, either through the quit button, the close X button, or the file menu.
void on_SaveGame ()
Handle when the user selected the save game button.
void on_SaveGameAs ()
Handle when the user selected the save game as button.
void on_TimerEvent ()
Handle when a timer event has been signaled.
void on_UndoMove ()
Handle when the user selected the undo move button.
void SetView (ChessView *view)
Set the ChessView that this ChessController will handle inputs for.
~ChessControllerImpl ()
Private Member Functions
void HighlightValidMoves (Piece *piece)
void UnHighlightValidMoves (Piece *piece)
void UpdateView ()
Private Attributes
Cell * currentCell
ChessGame * game
Piece * selectedPiece
ChessView * view
Constructor & Destructor Documentation
ChessControllerImpl::ChessControllerImpl ()
Constructor.
References DbgMsg, and selectedPiece.
ChessControllerImpl::ChessControllerImpl (ChessGame * game)
References DbgMsg, game, and selectedPiece.
ChessControllerImpl::~ChessControllerImpl ()
References DbgMsg.
Member Function Documentation
void ChessControllerImpl::HighlightValidMoves (Piece * piece) [private]
References game, ChessGame::GetValidMoves(), GREEN_SQUARE, ChessView::HighlightSquare(), and view.
Referenced by UpdateView().
void ChessControllerImpl::on_CellSelected (int row, int col, int button) [virtual]
Indicate to the player that the user clicked on the given row and column with the mouse.
Todo:
maybe speed up how we do this?
Implements ChessController.
References currentCell, DbgMsg, game, Piece::GetCell(), ChessGame::GetCell(), Piece::GetColor(), ChessGame::GetCurrentPlayersColor(), Cell::GetPiece(), ChessGame::IsValidMove(), ChessGame::Move(), ChessGame::PlayerInCheck(), ChessGame::PlayerInCheckMate(), selectedPiece, UpdateView(), and WHITE.
bool ChessControllerImpl::on_DragEnd (int row, int col) [virtual]
Parameters:
row where drag ended
col where drag ended
Returns:
true if the drag resulted in a successful drop
Implements ChessController.
References DbgMsgRC.
void ChessControllerImpl::on_DragStart (int row, int col) [virtual]
Parameters:
row where drag began
col where drag began
Implements ChessController.
References DbgMsgRC.
void ChessControllerImpl::on_LoadGame () [virtual]
Handle when the user selected the load game button.
Implements ChessController.
References DbgMsg.
void ChessControllerImpl::on_NewGame () [virtual]
Handle when the user selected the new game button.
Implements ChessController.
References DbgMsg, and UpdateView().
void ChessControllerImpl::on_QuitGame () [virtual]
Handle when the user selects to quit the game, either through the quit button, the close X button, or the file menu.
Implements ChessController.
References DbgMsg.
void ChessControllerImpl::on_SaveGame () [virtual]
Handle when the user selected the save game button.
Implements ChessController.
References DbgMsg.
void ChessControllerImpl::on_SaveGameAs () [virtual]
Handle when the user selected the save game as button.
Implements ChessController.
References DbgMsg.
void ChessControllerImpl::on_TimerEvent () [virtual]
Handle when a timer event has been signaled.
Implements ChessController.
void ChessControllerImpl::on_UndoMove () [virtual]
Handle when the user selected the undo move button.
Implements ChessController.
References DbgMsg.
void ChessControllerImpl::SetView (ChessView * view) [virtual]
Set the ChessView that this ChessController will handle inputs for.
Implements ChessController.
References DbgMsg, and view.
Referenced by main().
void ChessControllerImpl::UnHighlightValidMoves (Piece * piece) [private]
Note:
not currently using this function; also, this uses the old way of finding valid moves
void ChessControllerImpl::UpdateView () [private]
References BLUE_SQUARE, ChessView::ClearPiece(), game, Piece::GetCol(), Piece::GetImageName(), ChessGame::GetPiece(), Piece::GetRow(), ChessView::HighlightSquare(), HighlightValidMoves(), ChessView::PlacePiece(), selectedPiece, ChessView::UnHighlightSquare(), and view.
Referenced by on_CellSelected(), and on_NewGame().
Member Data Documentation
Cell* ChessControllerImpl::currentCell [private]
Referenced by on_CellSelected().
ChessGame* ChessControllerImpl::game [private]
Referenced by ChessControllerImpl(), HighlightValidMoves(), on_CellSelected(), and UpdateView().
Piece* ChessControllerImpl::selectedPiece [private]
Referenced by ChessControllerImpl(), on_CellSelected(), and UpdateView().
ChessView* ChessControllerImpl::view [private]
Referenced by HighlightValidMoves(), SetView(), and UpdateView().
The documentation for this class was generated from the following files:
ChessControllerImpl.h
ChessControllerImpl.cpp